package com.zhumei.baselib.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhumei.baselib.bean.scale.ScaleGoods;
import com.zhumei.baselib.bean.scale.ScaleHotkey;
import com.zhumei.baselib.bean.scale.ScaleTicket;
import com.zhumei.baselib.bean.scale.ScaleTrade;

import com.zhumei.baselib.dao.ScaleGoodsDao;
import com.zhumei.baselib.dao.ScaleHotkeyDao;
import com.zhumei.baselib.dao.ScaleTicketDao;
import com.zhumei.baselib.dao.ScaleTradeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig scaleGoodsDaoConfig;
    private final DaoConfig scaleHotkeyDaoConfig;
    private final DaoConfig scaleTicketDaoConfig;
    private final DaoConfig scaleTradeDaoConfig;

    private final ScaleGoodsDao scaleGoodsDao;
    private final ScaleHotkeyDao scaleHotkeyDao;
    private final ScaleTicketDao scaleTicketDao;
    private final ScaleTradeDao scaleTradeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        scaleGoodsDaoConfig = daoConfigMap.get(ScaleGoodsDao.class).clone();
        scaleGoodsDaoConfig.initIdentityScope(type);

        scaleHotkeyDaoConfig = daoConfigMap.get(ScaleHotkeyDao.class).clone();
        scaleHotkeyDaoConfig.initIdentityScope(type);

        scaleTicketDaoConfig = daoConfigMap.get(ScaleTicketDao.class).clone();
        scaleTicketDaoConfig.initIdentityScope(type);

        scaleTradeDaoConfig = daoConfigMap.get(ScaleTradeDao.class).clone();
        scaleTradeDaoConfig.initIdentityScope(type);

        scaleGoodsDao = new ScaleGoodsDao(scaleGoodsDaoConfig, this);
        scaleHotkeyDao = new ScaleHotkeyDao(scaleHotkeyDaoConfig, this);
        scaleTicketDao = new ScaleTicketDao(scaleTicketDaoConfig, this);
        scaleTradeDao = new ScaleTradeDao(scaleTradeDaoConfig, this);

        registerDao(ScaleGoods.class, scaleGoodsDao);
        registerDao(ScaleHotkey.class, scaleHotkeyDao);
        registerDao(ScaleTicket.class, scaleTicketDao);
        registerDao(ScaleTrade.class, scaleTradeDao);
    }
    
    public void clear() {
        scaleGoodsDaoConfig.clearIdentityScope();
        scaleHotkeyDaoConfig.clearIdentityScope();
        scaleTicketDaoConfig.clearIdentityScope();
        scaleTradeDaoConfig.clearIdentityScope();
    }

    public ScaleGoodsDao getScaleGoodsDao() {
        return scaleGoodsDao;
    }

    public ScaleHotkeyDao getScaleHotkeyDao() {
        return scaleHotkeyDao;
    }

    public ScaleTicketDao getScaleTicketDao() {
        return scaleTicketDao;
    }

    public ScaleTradeDao getScaleTradeDao() {
        return scaleTradeDao;
    }

}
